name: Content AI CI/CD
description: A Github Action for ContentAI
inputs:
  environment:
    description: ContentAI environment
    required: false
    default: prod
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.environment }}
